class_name INICIO_DA_PARTIDA_REFERENCIAS
extends Control


@onready var barra_de_tempo_selecao_racas:TextureProgressBar = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/BarraDeTempoSelecaoRacas
@onready var etiqueta_tempo_selecao_racas:Label = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/BarraDeTempoSelecaoRacas/EtiquetaTempoSelecaoRacas

@onready var miolo_selecao_racas:HBoxContainer = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas
@onready var retrato_anao:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoAnao/Marginalizador/RetratoAnao
@onready var retrato_besta:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoBesta/Marginalizador/RetratoBesta
@onready var retrato_dragao:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoDragao/Marginalizador/RetratoDragao
@onready var retrato_elemental:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoElemental/Marginalizador/RetratoElemental
@onready var retrato_elfo:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoElfo/Marginalizador/RetratoElfo
@onready var retrato_humano:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoHumano/Marginalizador/RetratoHumano
@onready var retrato_morto_vivo:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoMortoVivo/Marginalizador/RetratoMortoVivo
@onready var retrato_metamorfo:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoMetamorfo/Marginalizador/RetratoMetamorfo
@onready var retrato_naga:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoNaga/Marginalizador/RetratoNaga
@onready var retrato_pirata:TextureRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoPirata/Marginalizador/RetratoPirata
@onready var botao_selecionar_anao:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoAnao/Marginalizador/BotaoSelecionarAnao
@onready var botao_selecionar_besta:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoBesta/Marginalizador/BotaoSelecionarBesta
@onready var botao_selecionar_dragao:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoDragao/Marginalizador/BotaoSelecionarDragao
@onready var botao_selecionar_elemental:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoElemental/Marginalizador/BotaoSelecionarElemental
@onready var botao_selecionar_elfo:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoElfo/Marginalizador/BotaoSelecionarElfo
@onready var botao_selecionar_humano:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoHumano/Marginalizador/BotaoSelecionarHumano
@onready var botao_selecionar_metamorfo:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoMetamorfo/Marginalizador/BotaoSelecionarMetamorfo
@onready var botao_selecionar_morto_vivo:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoMortoVivo/Marginalizador/BotaoSelecionarMortoVivo
@onready var botao_selecionar_naga:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoNaga/Marginalizador/BotaoSelecionarNaga
@onready var botao_selecionar_pirata:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoRacas/OrganizadorRacas/PlanoDeFundoPirata/Marginalizador/BotaoSelecionarPirata

@onready var miolo_selecao_herois:HBoxContainer = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoHerois
@onready var selecionador_de_heroi_1:NinePatchRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoHerois/OrganizadorRacas/SelecionadorDeHeroi
@onready var selecionador_de_heroi_2:NinePatchRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoHerois/OrganizadorRacas/SelecionadorDeHeroi2
@onready var selecionador_de_heroi_3:NinePatchRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoHerois/OrganizadorRacas/SelecionadorDeHeroi3
@onready var selecionador_de_heroi_4:NinePatchRect = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/MioloSelecaoHerois/OrganizadorRacas/SelecionadorDeHeroi4

@onready var botao_confirmar:TextureButton = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/Centralizador/BotaoConfirmar
@onready var etiqueta_confirmar:Label = $PlanoDeFundoDoMiolo/Marginalizador/OrganizadorDeMiolo/Centralizador/BotaoConfirmar/EtiquetaConfirmar
