class_name INTERFACE_PRINCIPAL_REFERENCIAS
extends Control

@onready var imagem_rank = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/OrganizadorDeBarraDeRecurso/ImagemRank
@onready var etiqueta_gold = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/OrganizadorDeBarraDeRecurso/EtiquetaGold
@onready var etiqueta_pack = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/OrganizadorDeBarraDeRecurso/EtiquetaPack
@onready var etiqueta_level = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/OrganizadorDeBarraDeRecurso/EtiquetaLevel
@onready var pagina_home = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaHome
@onready var pagina_profile = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaProfile
@onready var pagina_decks = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaDecks
@onready var pagina_packs = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaPacks
@onready var pagina_loja = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaLoja
@onready var pagina_ranking = $BordaPlanoDeFundo/Marginalizador/OrganizadorDeInterface/ControladorDeAbasDoMiolo/PaginaRanking
