class_name INTERFACE_EM_PARTIDA_REFERENCIAS
extends Control

@onready var organizador_borda_esquerda:VBoxContainer = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda
@onready var mine_retrato_borda_1:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda1
@onready var mine_retrato_borda_2:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda2
@onready var mine_retrato_borda_3:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda3
@onready var mine_retrato_borda_4:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda4
@onready var mine_retrato_borda_5:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda5
@onready var mine_retrato_borda_6:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda6
@onready var mine_retrato_borda_7:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda7
@onready var mine_retrato_borda_8:NinePatchRect = $OrganizadorPrincipal/PlanoDeFundoBordaEsquerda/Marginalizador/OrganizadorBordaEsquerda/MineRetratoBorda8

@onready var retrato_taberneiro:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorRetratoTaberneiro/PlanoDeFundoRetratoTaberneiro/Marginalizador/RetratoTaberneiro
@onready var botao_melhorar:TextureButton = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorBotoesTaberna/BotaoMelhorar
@onready var botao_congelar:TextureButton = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorBotoesTaberna/BotaoCongelar
@onready var botao_atualizar:TextureButton = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorBotoesTaberna/BotaoAtualizar
@onready var taberna_slot_1:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorCartasTaberna/TabernaSlot1
@onready var taberna_slot_2:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorCartasTaberna/TabernaSlot2
@onready var taberna_slot_3:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorCartasTaberna/TabernaSlot3
@onready var taberna_slot_4:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorCartasTaberna/TabernaSlot4
@onready var pool_atual:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisSuperior/PoolAtual
@onready var etiqueta_pool_atual:Label = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisSuperior/EtiquetaPoolAtual
@onready var descarte_atual:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisSuperior/DescarteAtual
@onready var etiqueta_descarte_atual:Label = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisSuperior/EtiquetaDescarteAtual
@onready var retrato_icone_raca_1:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisInferior/RetratoIconeRaca1
@onready var retrato_icone_raca_2:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisInferior/RetratoIconeRaca2
@onready var retrato_icone_raca_3:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisInferior/RetratoIconeRaca3
@onready var retrato_icone_raca_4:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoTaberna/Marginalizador/OrganizadorMioloTaberna/OrganizadorInformacoesGerais/PlanoDeFundoInformacoesGerais/Marginalizador/PlanoDeFundo/OrganizadorMioloInformacoesGerais/OrganizadorInformacoesGeraisInferior/RetratoIconeRaca4

@onready var campo_slot_1:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot1
@onready var campo_slot_2:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot2
@onready var campo_slot_3:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot3
@onready var campo_slot_4:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot4
@onready var campo_slot_5:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot5
@onready var campo_slot_6:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot6
@onready var campo_slot_7:NinePatchRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoCampoDeBatalha/OrganizadorCampoDeBatalha/Marginalizador/OrganizadorCartasCampoDeBatalha/CampoSlot7

@onready var retrato_heroi:TextureRect = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoJogador/OrganizadorJogador/OrganizadorRetratoHeroi/PlanoDeFundoRetratoHeroi/Marginalizador/RetratoHeroi
@onready var botao_poder_heroi:TextureButton = $OrganizadorPrincipal/OrganizadorTaberna/PlanoDeFundoJogador/OrganizadorJogador/OrganizadorPoderHeroi/BotaoPoderHeroi
@onready var mao_slot_1:NinePatchRect = $OrganizadorMao/MaoSlot1
@onready var mao_slot_2:NinePatchRect = $OrganizadorMao/MaoSlot2
@onready var mao_slot_3:NinePatchRect = $OrganizadorMao/MaoSlot3
@onready var mao_slot_4:NinePatchRect = $OrganizadorMao/MaoSlot4
@onready var mao_slot_5:NinePatchRect = $OrganizadorMao/MaoSlot5
@onready var mao_slot_6:NinePatchRect = $OrganizadorMao/MaoSlot6
@onready var mao_slot_7:NinePatchRect = $OrganizadorMao/MaoSlot7

@onready var etiqueta_ouro:Label = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/EtiquetaOuro
@onready var ouro_slot_1:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot1
@onready var ouro_slot_2:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot2
@onready var ouro_slot_3:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot3
@onready var ouro_slot_4:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot4
@onready var ouro_slot_5:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot5
@onready var ouro_slot_6:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot6
@onready var ouro_slot_7:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot7
@onready var ouro_slot_8:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot8
@onready var ouro_slot_9:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot9
@onready var ouro_slot_10:TextureRect = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/OuroSlot10
@onready var barra_tempo_disponivel:TextureProgressBar = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/BarraTempoDisponivel
@onready var etiqueta_tempo_disponivel:Label = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/BarraTempoDisponivel/EtiquetaTempoDisponivel
@onready var botao_terminar_turno:TextureButton = $OrganizadorPrincipal/PlanoDeFundoBarraLateralDireita/Marginalizador/OrganizadorBarraLateralDireita/BotaoTerminarTurno

@onready var temporizador_de_turno:Timer = $TemporizadorDeTurno
