class_name OVERLAY_DE_INFORMACOES_REFERENCIAS
extends Control

@onready var retrato_heroi:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi
@onready var barra_vida:TextureProgressBar = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi/OrganizadorBarras/OrganizadorBarrasHorizontal/BarraVida
@onready var etiqueta_vida:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi/OrganizadorBarras/OrganizadorBarrasHorizontal/BarraVida/Marginalizador/IconeVida/EtiquetaVida
@onready var barra_escudo:TextureProgressBar = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi/OrganizadorBarras/OrganizadorBarrasHorizontal/BarraEscudo
@onready var etiqueta_escudo:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi/OrganizadorBarras/OrganizadorBarrasHorizontal/BarraEscudo/Marginalizador/IconeEscudo/EtiquetaEscudo
@onready var etiqueta_ataque:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorDeRetrato/PlanoDeFundoRetrato/Marginalizador/RetratoHeroi/OrganizadorBarras/OrganizadorBarrasHorizontal/PlanoDeFundoAtaque/Marginalizador/IconeAtaque/EtiquetaAtaque

@onready var etiqueta_nick:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/EtiquetaNick
@onready var etiqueta_nome_heroi:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/EtiquetaNomeHeroi

@onready var etiqueta_racas:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/PlanoDeVidaRacas/Marginalizador/TexturaDeFundoRacas/EtiquetaRacas
@onready var icone_taverna:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorIcones/IconeTaverna
@onready var icone_triplos:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorIcones/IconeTriplos
@onready var etiqueta_triplos:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorIcones/IconeTriplos/EtiquetaTriplos
@onready var icone_streak:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorIcones/IconeStreak

@onready var retrato_inimigo_1:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida1/PlanoDeFundoInimigo1/Marginalizador/RetratoInimigo1
@onready var etiqueta_dano_causado_1:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida1/EtiquetaDanoCausado1
@onready var icone_dano_recebido_ou_causado_1:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida1/Espacador/IconeDanoRecebidoOuCausado1
@onready var etiqueta_dano_recebido_1:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida1/EtiquetaDanoRecebido1
@onready var retrato_heroi_1:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida1/PlanoDeFundoHeroi1/Marginalizador/RetratoHeroi1

@onready var retrato_inimigo_2:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida2/PlanoDeFundoInimigo2/Marginalizador/RetratoInimigo2
@onready var etiqueta_dano_causado_2:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida2/EtiquetaDanoCausado2
@onready var icone_dano_recebido_ou_causado_2:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida2/Marginalizador/IconeDanoRecebidoOuCausado2
@onready var etiqueta_dano_recebido_2:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida2/EtiquetaDanoRecebido2
@onready var retrato_heroi_2:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida2/PlanoDeFundoHeroi2/Marginalizador/RetratoHeroi2

@onready var retrato_inimigo_3:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida3/PlanoDeFundoInimigo3/Marginalizador/RetratoInimigo3
@onready var etiqueta_dano_causado_3:Label = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida3/EtiquetaDanoCausado3
@onready var icone_dano_recebido_ou_causado_3:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida3/Marginalizador/IconeDanoRecebidoOuCausado3
@onready var retrato_heroi_3:TextureRect = $PlanoDeFundo/Marginalizador/OrganizadorDeMiolo/OrganizadorResultadoPartida3/PlanoDeFundoHeroi3/Marginalizador/RetratoHeroi3
