class_name PAGINA_HOME_REFERENCIAS
extends VBoxContainer

@onready var imagem_carrossel:TextureRect = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/ImagemCarrossel
@onready var plano_defundo_texto_carrossel:Panel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/ImagemCarrossel/OrganizadorMioloCarrossel/PlanoDefundoTextoCarrossel
@onready var texto_carrossel:RichTextLabel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/ImagemCarrossel/OrganizadorMioloCarrossel/PlanoDefundoTextoCarrossel/TextoCarrossel
@onready var imagem_auxiliar_1: TextureRect = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar1
@onready var plano_de_fundo_texto_imagem_auxiliar_1:Panel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar1/OrganizadorTextoImagemAuxiliar1/PlanoDeFundoTextoImagemAuxiliar1
@onready var texto_imagem_auxiliar_1:RichTextLabel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar1/OrganizadorTextoImagemAuxiliar1/PlanoDeFundoTextoImagemAuxiliar1/OrganizadorTextoImagemAuxiliar1
@onready var imagem_auxiliar_2: TextureRect= $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar2
@onready var plano_de_fundo_texto_imagem_auxiliar_2:Panel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar2/OrganizadorTextoImagemAuxiliar2/PlanoDeFundoTextoImagemAuxiliar2
@onready var texto_imagem_auxiliar_2:RichTextLabel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar2/OrganizadorTextoImagemAuxiliar2/PlanoDeFundoTextoImagemAuxiliar2/OrganizadorTextoImagemAuxiliar2
@onready var imagem_auxiliar_3: TextureRect= $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar3
@onready var plano_de_fundo_texto_imagem_auxiliar_3:Panel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar3/OrganizadorTextoImagemAuxiliar3/PlanoDeFundoTextoImagemAuxiliar3
@onready var texto_imagem_auxiliar_3:RichTextLabel = $OrganizadorMioloHome/OrganizadorVerticalCarrosselHome/OrganizadorHorizontalCarrosselHome/OrganizadorImagensAuxiliares/ImagemAuxiliar3/OrganizadorTextoImagemAuxiliar3/PlanoDeFundoTextoImagemAuxiliar3/OrganizadorTextoImagemAuxiliar3
@onready var barra_level:TextureProgressBar = $OrganizadorBarraLevel/BarraLevel
